### ISSUE TITLE
_computeMediaQuery never called on Firefox

### ISSUE THREAD

**Issue by johnheroy** [PolymerElements/paper-drawer-panel#100]
I have a `<paper-drawer-panel>` with a right drawer which works on Chrome (in shady DOM) but not in Firefox or iOS Safari. I found that the _computeMediaQuery method never gets called so the 'query' prop on <iron-media-query> is undefined and thus the parent `<paper-drawer-panel>` never gets a .narrow-layout class which triggers [this style](https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.css#L119) and actually slides away the drawer. Any thoughts?

**Comment by johnheroy** [comment]
forceNarrowChanged also never called, wonder if it has anything to do with https://github.com/PolymerElements/paper-drawer-panel/issues/26?

**Comment by frankiefu** [comment]
I can't reproduce that problem you mentioned.  For example, this [jsbin](http://jsbin.com/nohajefada/edit?html,output) works on Firefox and Safari.

**Comment by johnheroy** [comment]
I am having trouble producing a simple example which I can share here and repros the problem, I created this [jsbin](http://jsbin.com/videdomike/edit?html,output) which shows what we are doing (create paper-drawer-panel inside div and then attach div to the DOM). Btw I am using vulcanize and the lite version of the polyfill and compiling the components + deps with the closure compiler.

**Comment by blasten** [comment]
It could potentially be a timing issue in webcomponent.js. I have seem similar issues in the past; however, to effectively determinate the causes and its implication, I need to debug the code. Feel free to ping me in GH.
