### ISSUE TITLE
paper-drawer-toggle not working on paper-icon-button in paper-toolbar

### ISSUE THREAD

**Issue by kritollm** [PolymerElements/paper-drawer-panel#113]
Polymer.dom(event).localTarget gives the reference to the paper-drawer-panel. Not the clicked button, and even if it did it wouldn't work because the event.target is the iron-icon inside the paper-icon-button

```
<paper-icon-button paper-drawer-toggle icon="more-vert" ></paper-icon-button> 
```

didn't work so I had to change _onTap to this:

```
   _onTap: function(event) {
          var targetElement = Polymer.dom(event).rootTarget;
          var isTargetToggleElement = targetElement &&
                  (targetElement.hasAttribute(this.drawerToggleAttribute) || (targetElement.domHost && targetElement.domHost.hasAttribute(this.drawerToggleAttribute)));

      if (isTargetToggleElement) {
        this.togglePanel();
      }
    },
```

To reproduce the problem, add this line:

```
<paper-icon-button paper-drawer-toggle icon="more-vert" ></paper-icon-button>
```

under this line:

```
<paper-toolbar>
```

In the input-header.html in this demo https://github.com/kevinpschaaf/chat-view-paper

**Comment by kritollm** [comment]
Perhaps the paper-drawer-panel component could search for the button that has drawerToggleAttribute once and then store the attribute on the target. Then you could compose custom buttons and it would still work.

**Comment by kritollm** [comment]
By clipping out the <paper-toolbar> element from the <chat-thread-view > element and paste it in the main app element it worked.

So it looks like it will be a lot of problems when composing new elements because they work different based on where they are placed, although in theory, at the same place in the doom-tree.

I think Polymer is great, but it's not a "it just work" library :)

**Comment by mercmobily** [comment]
Sorry to ask you but... how did you fix the problem exactly...?

**Comment by kritollm** [comment]
I think #60 may solve the problem.
