### ISSUE TITLE
Clicking on paper-icon-button[paper-drawer-toggle] doesn't open the drawer

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-drawer-panel#12]
If you adjust the demo to use `<paper-icon-button>` instead of `<button>`, the drawer doesn't slide out when you click the icon button.

``` html
    <paper-drawer-panel id="paperDrawerPanel">
      <div drawer></div>
      <div main>
        <div>
          <button onclick="flipDrawer()">flip drawer</button>
        </div>
        <div>
          <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
        </div>
      </div>
    </paper-drawer-panel>
```

cc @robdodson

**Comment by michaelpg** [comment]
could this be merged into 0.8? I think it's causing a similar issue.

I have a `<paper-menu>` (0.8.3) inside the drawer of a `<paper-drawer-panel>`.

In iron-selectable's _itemActivate function, it fires an `iron-activate` event. Normally the event is not caught and `this.select(value)` is called to select the item.

In my case, the paper-drawer-panel is catching the `iron-activate` event with its `onSelect` method and calling `preventDefault()`, preventing the menu items from being selected.
