### ISSUE TITLE
mini variant missing feature

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/paper-drawer-panel#120]
From [spec](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior)

> Mini variant
> 
> In this variation, the persistent navigation drawer changes its width. Its resting state is as a mini-drawer at the same elevation as the content, clipped by the app bar. When expanded, it appears as the standard persistent navigation drawer.
> 
> […]
> 
> The mini variant is also an acceptable closed state for a temporary navigation drawer.

<img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ZVZzVEhrbF9YWk0/patterns_navdrawer_behavior_persistent4.png" width="200"><img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7TEVnWVlVS3RXMzQ/patterns_navdrawer_behavior_persistent5.png" width="200">

Would be a usefull feature, it's a challenge to have a fluid and logic transition. Any suggestions ?

**Comment by blasten** [comment]
+1 for sure. I moved the issue to https://github.com/PolymerLabs/app-layout/issues/39
