### ISSUE TITLE
AutoFocus results into infinite loop of refocusing

### ISSUE THREAD

**Issue by TomasAgoston** [PolymerElements/paper-drawer-panel#134]
With the new version 1.0.7 we get a infinite loop of refocusing on the drawer panel.

We have a drawer panel in our app (actually there are two nested drawer panels) and in that panel we have menu with submenus (multilevel hierarchical menu). On opening and closing of submenus we are modifing the selection in those menus.

With version 1.0.6 of the paper-drawer-panel everything is working OK.

Upgrading to version 1.0.7 results into calls of iron-menu-behaviour's  _onFocus handler and the async call of _defaultFocusAsync when opening and closing the submenus. 

See the attached screenshot from Chrome's Timeline.  You can see the repetative calls in the first row of "Timeline data". The "problematic" timer call is selected with the stack trace.

![paper_drawer_panel_focus_cycle_160307](https://cloud.githubusercontent.com/assets/1176792/13581453/38324a00-e4a7-11e5-8f80-34fb267ff2e7.png)

**Comment by frankiefu** [comment]
Can you post a jsbin that can reproduce the issue?

**Comment by blasten** [comment]
@TomasAgoston 

Can you run `bower i PolymerElements/paper-drawer-panel#focus-patch` to see if that fixes the issue?

The main issue here seems to be related to async focus retargeting: https://github.com/PolymerElements/iron-menu-behavior/blob/master/iron-menu-behavior.html#L265-L266

**Comment by TomasAgoston** [comment]
Sorry for the late response.

The current version 1.0.9 works fine. Thanks for the fix.
