### ISSUE TITLE
paper-drawer-panel.html:823 Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by marxtseng** [PolymerElements/paper-drawer-panel#136]
[https://github.com/MarxTseng/paper-drawer-panel-maximum-call-stack](url)

When I use the "paper-drawer-panel", at the same time open two "drawer panel", if the "drawer panel" contains "dom-repeat" or "paper-input", can cause this problem.

**Comment by frankiefu** [comment]
Here is a jsbin that reproduces the issue: http://jsbin.com/robahobuye/edit?html,output

**Comment by blasten** [comment]
@MarxTseng can you test `bower i PolymerElements/paper-drawer-panel#focus-patch`

**Comment by blasten** [comment]
@MarxTseng Did it fix the issue in your code?

**Comment by marxtseng** [comment]
@blasten Thanks very much, the issue is fix in my code.

**Comment by blasten** [comment]
sweet
