### ISSUE TITLE
Default responsiveWidth should be wider

### ISSUE THREAD

**Issue by joryphillips** [PolymerElements/paper-drawer-panel#138]
Problem: If the window is 601px wide, the drawer defaults to nearly half the width of the screen. This is not great functionally or visually.

Solution: change default responsive width for hiding the drawer to 840px, instead of 600px. Then the drawer is less than a third of the screen, which is a lot more comfortable. 768px would work too, but I like 840 because it's already a standard width in the library.

**Comment by blasten** [comment]
That would be a breaking change and I'm sure most people are relying on the default `600px`. I'd advise changing the `responsiveWidth`  manually.

**Comment by samccone** [comment]
Hmm, just because it is breaking does not mean it is not a valid concern eh?

Question: if we were to make this change and then bump our semver a major point, we would be A-OK right?

So long as we noted the change in the changelog we should be all covered.

**Comment by blasten** [comment]
@samccone that is true. I'm inclined to think that the default value could be adjusted to `768px`. PR welcome :)
