### ISSUE TITLE
Uncaught TypeError: Cannot set property 'touchAction' of undefined

### ISSUE THREAD

**Issue by matheusdavidson** [PolymerElements/paper-drawer-panel#14]
While testing the component demo with polymer 0.9 i've got this message on the console.
Error is in gesture.html, line 222:
`node.style.touchAction = value;`

**Comment by chuckh** [comment]
I got the same error too. The demo will still loaded ok for me. But my app using paper-drawer-panel stopped loading using 0.9.2. I rolled back to 0.9.1 everything worked ok. This is the error for 0.9.2:

```
Uncaught TypeError: Cannot set property 'touchAction' of undefined
gestures.html:222
```

**Comment by addyosmani** [comment]
Confirmed. cc @notwaldorf

**Comment by notwaldorf** [comment]
Passing the hot potato to @azakus, who's been working on gestures. :)

**Comment by dfreedm** [comment]
Whoops, I changed the `setScrollDirection` API in the polymer master branch, but it is not represented in an RC yet.

**Comment by addyosmani** [comment]
To work around this for now, should we locally lock in to a specific commit from the polymer master branch or is another RC imminent?

**Comment by dfreedm** [comment]
That should be decided very soon. I'll make the update either way after that decision is made.

**Comment by addyosmani** [comment]
Awesome. Thanks @azakus :)

**Comment by mbleigh** [comment]
FYI if you're following along and it's still before Polymer `0.9.0-rc.2` or whatever the next release is, you can get around this by locking Polymer down to the `0.8-preview` branch which includes gestures now.
