### ISSUE TITLE
Does paper-drawer-panel not work with Polymer 0.5.1 ?

### ISSUE THREAD

**Issue by robs15** [PolymerElements/paper-drawer-panel#144]
### Description

Paper drawer panel is added into DOM when inspected in browser, but is not displaying. Polymer version being used is 0.5.1. Panel is being added in another polymer element. While trying to access the openDrawer() method, it says, method is undefined.
### Expected outcome

Panel should work as seen in examples on polymer site.

### Actual outcome

Panel is seen in DOM but not visible.
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

![pdperror1](https://cloud.githubusercontent.com/assets/10429704/16830658/e0689d3e-49bd-11e6-86ba-f6cc73dab9b0.jpg)
![pdperror2](https://cloud.githubusercontent.com/assets/10429704/16830686/0a5ea840-49be-11e6-8ccf-fd5980fd328c.jpg)

**Comment by notwaldorf** [comment]
Unfortunately not; this element (and all elements in the `PolymerElements` org only work with Polymer 1.0 (also an [explicit](https://github.com/PolymerElements/paper-drawer-panel/blob/master/bower.json#L25) dependency in bower)

**Comment by robs15** [comment]
Thanks @notwaldorf !
