### ISSUE TITLE
Disable flying drawer animation when rightDrawer is changed

### ISSUE THREAD

**Issue by minhlong139** [PolymerElements/paper-drawer-panel#149]
I have both right and left drawer on a page so properties rightDrawer change on-the-fly. 

When rightDrawer changed, the drawer fly from left to right made confusing for user so I want to disabled this animation, how can I do that? 

![nimbus-record-video](https://cloud.githubusercontent.com/assets/171335/17547911/8e4a1076-5f13-11e6-8b43-c65ff06de20e.gif)

**Comment by minhlong139** [comment]
+1

**Comment by blasten** [comment]
That's a good point. Feel free to send a PR to fix that issue.

**Comment by t-soares** [comment]
@blasten Can you close this?

**Comment by blasten** [comment]
yup

**Comment by jaichandra** [comment]
This issue is still not fixed. See the transition in below plnkr, when the hamburger menu is clicked for the first time. 
https://plnkr.co/edit/MvP1oBCIF0eAI4COi4kk?p=preview

**Comment by t-soares** [comment]
@jaichandra It is fixed, but it is not included in the 1.7.0 lib that you are referring on your code. Change the link to https://cdn.rawgit.com/download/polymer-cdn/master/lib/

**Comment by jaichandra** [comment]
@tas1982 awesome. Thanks. Is it available in 1.8.1? BTW.. do you mind sharing some details on how this is related to Polymer version? Is this Polymer 2.0 that fixes this issue?
