### ISSUE TITLE
paper-drawer-panel demo is not working as expected.

### ISSUE THREAD

**Issue by anishcodes** [PolymerElements/paper-drawer-panel#15]
# Environment:

Chrome Version 42.0.2311.135 (64-bit) on mac.

bower.json dependencies:
  "dependencies": {
    "polymer": "polymer/polymer#v0.9.0-rc.1",
    "paper-drawer-panel": "PolymerElements/paper-drawer-panel#^0.9.2"
  }
# Issue:

The toggle button (<button paper-drawer-toggle>toggle drawer</button>) does not appear and also the drawer does not hide when browser's width is reduced.
# Error:

GET http://localhost:8000/bower_components/paper-styles/demo.css 404 (File not found)
localhost/:20 GET http://localhost:8000/bower_components/paper-styles/default-theme.html 404 (File not found)
gestures.html:222 Uncaught TypeError: Cannot set property 'touchAction' of undefinedGestures.setTouchAction @ gestures.html:222Polymer.Base._addFeature.setScrollDirection @ gestures.html:437Polymer._responsiveChange @ paper-drawer-panel.html:566Polymer.onQueryMatchesChanged @ paper-drawer-panel.html:571(anonymous function) @ events.html:62Polymer.Base._addFeature.fire @ utils.html:157Polymer.Bind._modelApi._notifyChange @ accessors.html:31Polymer.Base.extend._notifyEffect @ effects.html:42(anonymous function) @ accessors.html:71Polymer.Bind._modelApi._effectEffects @ accessors.html:67Polymer.Bind._modelApi._propertySet @ accessors.html:60Polymer.Base._addFeature._applyConfig @ configure.html:152Polymer.Base._addFeature._afterClientsReady @ configure.html:135Polymer.Base._addFeature._ready @ ready.html:98Polymer.Base._addFeature._readyClients @ ready.html:110Polymer.Base._addFeature._ready @ ready.html:96Polymer.Base._addFeature._tryReady @ ready.html:85Polymer.Base._addFeature._initFeatures @ polymer.html:76Polymer.Base.createdCallback @ base.html:30
gestures.html:222 Uncaught TypeError: Cannot set property 'touchAction' of undefined

**Comment by matheusdavidson** [comment]
i think its the same issue i had(see https://github.com/PolymerElements/paper-drawer-panel/issues/14)
For now the option is to use paper-drawer-panel 0.9.1 version, update your bower to :
`"paper-drawer-panel": "PolymerElements/paper-drawer-panel#0.9.1"`
