### ISSUE TITLE
[2.0-preview] The first focusable item should be focused when the drawer is opened

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-drawer-panel#167]
When the drawer is opened, it is supposed to auto focus the first focusable item inside the drawer.  But in 2.0-preview it doesn't.

### Expected outcome

The first button inside the drawer should be focused.

### Actual outcome

Nothing is focused when the drawer is opened.

### Steps to reproduce

1. Run the paper-drawer-panel demo.
2. Click the `OPEN DRAWER` button.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 10
- [x] Safari 9
- [x] Edge
- [x] IE 11

**Comment by blasten** [comment]
Fixed in https://github.com/PolymerElements/paper-drawer-panel/commit/e467a01c77b22d527b804fe3df3878a73f9d5fc6
