### ISSUE TITLE
forceNarrow not hiding the drawer

### ISSUE THREAD

**Issue by matheusdavidson** [PolymerElements/paper-drawer-panel#17]
i have a narrow layout type so im using forceNarrow to hide the drawer on larger screen(will show later only on mobile devices by clicking some button).

The drawer will not close with this:
`<paper-drawer-panel forceNarrow narrow id="paperDrawerPanel">`

**Comment by matheusdavidson** [comment]
its not hiding because the correct attribute is force-narrow instead of forceNarrow

**Comment by AndreasGalster** [comment]
https://elements.polymer-project.org/elements/paper-drawer-panel The docs say it's forceNarrow.

**Comment by notwaldorf** [comment]
The property is indeed `forceNarrow`, but when used as an html attribute, it needs to be specified as `force-narrow` (see: https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping)
