### ISSUE TITLE
Changing forceNarrow from true to false is forcing the drawer to display even in mobile view

### ISSUE THREAD

**Issue by BramKleinhout** [PolymerElements/paper-drawer-panel#18]
While changing the forceNarrow attribute from 'true' to 'false' the drawer is forced to display, without checking if the drawer should be displayed at current document width. If the document width is smaller then the responsiveWidth, the drawer should not automatically being displayed.

``` js
forceNarrowChanged: function() {
  this._responsiveChange(this.forceNarrow);
}
```

Setting forceNarrow to 'false' _responsiveChange is called passing 'false'

``` js
_responsiveChange: function(narrow) {
  this.narrow = narrow; 

  if (this.narrow) {
    this.selected = this.defaultSelected;
  }

  this.setAttribute('touch-action', this.swipeAllowed() ? 'pan-y' : '');
  this.fire('paper-responsive-change', {narrow: this.narrow});
}
```

 The default display is forced at this point, because 'narrow' is 'false', but this.narrow should be 'true' though.

**Comment by blasten** [comment]
This has been fixed in master.
