### ISSUE TITLE
Drag & Drop Broken

### ISSUE THREAD

**Issue by kevashcraft** [PolymerElements/paper-drawer-panel#20]
Elements are not draggable inside the drawer-panel's content area.

<div draggable="true>drag me</div>

Adding the draggable attribute causes the element's text to not be selectable, but does not fire any of the ondrag\* events nor allow the element to be grabbed visually.

**Comment by blasten** [comment]
Do you have a drag & drop kind of thing?

**Comment by blasten** [comment]
Can you provide a example to replicate the issue?

**Comment by kevashcraft** [comment]
The issue appears to be resolved with newer versions :)
