### ISSUE TITLE
Offsetting core drawer panel

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-drawer-panel#25]
I would like to know if we can offset the core drawer panel when the toggle button is clicked so that the drawer scrolls after the toggle button but still the toggle button should be active to be clicked on again to hide the drawer panel.
Also is it possible to make the core drawer panel scroll from bottom, say an options bar that when toggled will scroll up from bottom.

Thanks

**Comment by blasten** [comment]
@VigneshVaidyanathan  we have plans to support this in the future. For know, you could add a hide button to the drawer.

**Comment by blasten** [comment]
You can use a `paper-toolbar` and  add a toggle button to it:

``` html
<paper-drawer-panel>
  <paper-header-panel drawer>
    <paper-toolbar>Menu</paper-toolbar>
  </paper-header-panel>
  <paper-header-panel main>
    <paper-toolbar>
      <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
      <div class="title">My App</div>
    </paper-toolbar>
  </paper-header-panel>
</paper-drawer-panel>
```
