### ISSUE TITLE
forceNarrow's observer is setup incorrectly

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-drawer-panel#26]
There is an observer for the property `forceNarrow`:

```
forceNarrow: {
  observer: 'forceNarrowChanged',
  type: Boolean,
  value: false
},
```

but `forceNarrowChanged` also relies on the property `defaultSelected` and there is no guarantee that you get all the configured values before observers run.  So it is better to make sure the observer declare all the dependent properties.

A possible fix:

```
observers: [
  'forceNarrowChanged(forceNarrow, defaultSelected)'
],
```

**Comment by blasten** [comment]
Fixed now!
