### ISSUE TITLE
edgeSwipeOverlay blocks menu toggle button on mobile

### ISSUE THREAD

**Issue by harsimranmaan** [PolymerElements/paper-drawer-panel#28]
``` html
<div id="edgeSwipeOverlay" class="style-scope paper-drawer-panel">
        </div>
```

When rendering the drawer panel on a mobile device(Nexus 5) the edgeSwipeOverlay overlaps the toggle menu button in in the main drawer as well parts of elements in the main panel(near left edge). As a workaround I added left margin to all elements in the main panel.

**Comment by blasten** [comment]
What version are you using?  We have removed `edgeSwipeOverlay`, but I noticed that we haven't tagged it yet.  Meanwhile, you can download the latest paper-drawer-panel from master https://github.com/PolymerElements/paper-drawer-panel/archive/master.zip
