### ISSUE TITLE
drawerWidth is not applied

### ISSUE THREAD

**Issue by s850042002** [PolymerElements/paper-drawer-panel#31]
Try to adapt the drawerWidth, but it's not working. Below is the modified demo page.

```
    <paper-drawer-panel id="paperDrawerPanel" drawerWidth="512px">
      <div drawer>I am drawer</div>
      <div main>
        <div>
          <paper-button onclick="flipDrawer()" raised>flip drawer</paper-button>
        </div>
        <div>
          <paper-button paper-drawer-toggle raised>toggle drawer</paper-button>
        </div>
      </div>
    </paper-drawer-panel>
```

**Comment by s850042002** [comment]
Same issue as #17 , `drawer-width` should be good. but the code in `paper-drawer-panel.html` is still

```
drawerWidth: {
          type: String,
          value: '256px'
        }
```

can someone tell me why?

**Comment by frankiefu** [comment]
camel-case properties of elements using attributes, dash- case should be used in the attribute name.
https://www.polymer-project.org/0.9/docs/devguide/properties.html#attribute-deserialization
So it should be:

```
<paper-drawer-panel id="paperDrawerPanel" drawer-width="512px">
```

**Comment by s850042002** [comment]
Thanks a lot :)
