### ISSUE TITLE
responsiveWidth change not works

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-drawer-panel#43]
Changing responsiveWidth="800px", _computeMediaQuery log still 640px

**Comment by Sopamo** [comment]
This does work, when you use responsive-width instead of responsiveWidth on the <paper-drawer-panel>. Should be changed or noted in the documentation somewhere.

**Comment by tdesc** [comment]
Correct, responsive-width do work. Thanks

**Comment by renfeng** [comment]
Bumped into the same problem. And, here is the doc
https://www.polymer-project.org/1.0/docs/migration.html#property-name-to-attribute-name-mapping
