### ISSUE TITLE
bug in documentation

### ISSUE THREAD

**Issue by felislynx-silae** [PolymerElements/paper-drawer-panel#44]
In documentation attribute forceNarrow should be changed to force-narrow. I've lost few hours on resolving this :)

**Comment by SuperiorJT** [comment]
Same here, I think all of the attributes have been changed to that format now. I thought I was going to have to write my own element just to start the drawer closed!

**Comment by s850042002** [comment]
I asked the same question in #31, frankiefu gave the answer, [attribute-deserialization](https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization).

**Comment by SuperiorJT** [comment]
Maybe they should consider mentioning this in the [Usage Guide](https://elements.polymer-project.org/guides/using-elements) so that people aren't confused about this in the future.

**Comment by blasten** [comment]
@SuperiorJT that's a good point.

**Comment by MGRProgramming** [comment]
same for "disableSwipe" - now "disable-swipe" and most likely other properties.
Please update documentation - Thanks!

**Comment by blasten** [comment]
@arthurevans is this clear in the docs?

**Comment by arthurevans** [comment]
Agree with @SuperiorJT & I've opened a issue to track this -- https://github.com/Polymer/polymer-element-catalog/issues/90

**Comment by blasten** [comment]
thanks @arthurevans !

**Comment by matfin** [comment]
Hi,

Just started going through the documentation for this component it appears a lot of the content is still incorrect. The URL is as follows:

https://elements.polymer-project.org/elements/paper-drawer-panel#property-drawerWidth

For example, I tried the following 

```
<!-- This did not work! -->
<paper-drawer-panel forceNarrow="true" id="paper_drawer_panel">

<!-- This did work -->
<paper-drawer-panel force-narrow="true" id="paper_drawer_panel">
```

Documentation definitely needs to be updated.

Thanks,

Matt
