### ISSUE TITLE
menu button paper-drawer-toggle bug with opened drawer in narrow mode

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-drawer-panel#47]
menu button paper-drawer-toggle acts when click on opened drawer panel 
It is not visible under drawer, but takes action.
bug appears without anything on drawer and also with some content over it.

``` html
 <div drawer>
       <paper-menu class="list">
               <paper-item>Inbox</paper-item>
               <paper-item>Starred</paper-item>
               <paper-item>Sent mail</paper-item>
               <paper-item>Drafts</paper-item>
       </paper-menu>
</div>
```

**Comment by blasten** [comment]
this is also related to https://github.com/PolymerElements/paper-drawer-panel/issues/55

**Comment by blasten** [comment]
@tdesc This is fixed now in `paper-toolbar`. Can you update it via `bower update` ?

**Comment by tdesc** [comment]
Thanks!

2015-06-12 21:47 GMT+03:00 Emmanuel Garcia notifications@github.com:
