### ISSUE TITLE
Menu wrongly shows up on Firefox (Desktop/Mobile) if mouse/finger is moved to the right

### ISSUE THREAD

**Issue by nhnb** [PolymerElements/paper-drawer-panel#48]
On Chrome the menu panel only shows up, if the menu button is pressed, or the mouse/finger is dragged from the left corner a little to the right.

On Firefox, however, the screen will turn grey on any movement anywhere of the main panel. If the move ends a little right of the starting point, the menu will show up. The touch-movement indicated in red on the screenshot should not open the menu.

This behavior occurs on both Firefox mobile on Android and Firefox desktop on Ubuntu.

![touch](https://cloud.githubusercontent.com/assets/364184/7937736/248a443a-0942-11e5-9ee3-1a780d8e13e2.png)

**Steps to reproduce:**
1. In Firefox go to https://elements.polymer-project.org/bower_components/paper-drawer-panel/demo/index.html
2. Shrink the window until the drawer is hidden
3. Press the mouse button anywhere (e. g., far from the left border), move the mouse a little to the right, release mouse button

**Expected behaviour:**
Nothing happens

**Actual behaviour on Firefox (mobile/desktop):**
The drawer shows up.

**Comment by jenishngl** [comment]
Me too have this issue in Firefox on my desktop running windows 8.1(my current version is 38.0.5) and on my Android Phone. It works fine in IE and chrome.

**Comment by blasten** [comment]
This is related to https://github.com/PolymerElements/paper-drawer-panel/issues/56

**Comment by blasten** [comment]
It's fixed now in master.
