### ISSUE TITLE
iPhone loading issues

### ISSUE THREAD

**Issue by SuperiorJT** [PolymerElements/paper-drawer-panel#49]
Running a drawer on iPhone Chrome and Safari takes an unreasonably long time to load the element along. Along with this, the drawer is shown during this load period even with force-narrow set to true. I have only tested this with an iPhone 5 on iOS 8.3. If anybody needs an example, my website is currently running it at [jlmiller.guru](http://www.jlmiller.guru).

**Comment by SuperiorJT** [comment]
Actually, this seems to be happening on some other machines, not just iPhone. My macbook air, however, runs it just fine; along with my Galaxy S4 on 4.4.2.

**Comment by blasten** [comment]
@SuperiorJT You should add the attribute `unresolved` to the `body` element. For example:

``` html
<body unresolved>
```
