### ISSUE TITLE
Selecting content inside the component

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-drawer-panel#50]
Any content that is child from paper-drawer-panel can't be properly selected - just one character can be selected by click and drag whereas double-click: selects everything around or a word as usual.

Demo: https://peduxe.herokuapp.com/paper-drawer-panel.html

Browser: Chrome 43.0.2357.81 (64-bit) Linux

**Comment by blasten** [comment]
It's confirmed. @azakus is this the expected behavior?  The `track` event is canceling the selection because `paper-drawer-panel` has a global listener.

**Comment by frankiefu** [comment]
Also if you put the content on the drawer and if you try to select the text, that will make the drawer to move.  We need a way to do text selection without making the drawer to move.
