### ISSUE TITLE
paper-drawer-toggle attribute wont work if nested in another custom-element

### ISSUE THREAD

**Issue by namiwang** [PolymerElements/paper-drawer-panel#60]
Say I've got a construct like this: 

```
<drawer>
  <div drawer>
  </div>
  <div main>
    <another-custom-element>
    </another-custom-element>
  </div>
<drawer>
```

And that `<another-custom-element>` includes a `<paper-icon paper-drawer-toggle>`

Then it wont toggle the drawer automatically.

**Comment by blasten** [comment]
@nanowang  that's because `<paper-icon paper-drawer-toggle>` is in the shadow dom of `<another-custom-element>`  

You should use:

``` html
<another-custom-element>
  <paper-icon paper-drawer-toggle>
 </another-custom-element>
```

and have a `<content select="[paper-drawer-toggle]"></content>` in the shadow dom of `another-custom-element`
