### ISSUE TITLE
does not work in iron/neon pages

### ISSUE THREAD

**Issue by senfgurke** [PolymerElements/paper-drawer-panel#62]
Hi,

I like polymer... but I found an error, I think. I'm building on a desktop app with nw.js and using polymer 1.0.3  as UI-System...

Szenario:
- Landing/ Welcome - Page 
- my app-element with paper-drawer-panel 
- both are in neon-animated-pages in a neon-animatable element, but the app-element doesn't show anything --> i tried the same with iron-pages

when I use the app-element as main element without a pages element... the drawer renders and i can see my toolbar...

**Comment by blasten** [comment]
@senfgurke I tested the following in `neon-animation/demo/declarative/index.html`but I couldn't replicate the issue. Please provide a link or something to simulate the issue.

``` html
<link rel="import" href="../../../paper-drawer-panel/paper-drawer-panel.html">
<link rel="import" href="../../../paper-header-panel/paper-header-panel.html">
<link rel="import" href="../../../paper-toolbar/paper-toolbar.html">
```

``` html
<neon-animated-pages id="pages" class="flex" selected="[[selected]]" entry-animation="[[entryAnimation]]" exit-animation="[[exitAnimation]]">
  <neon-animatable>
    <paper-drawer-panel>
      <paper-header-panel drawer>
        <paper-toolbar>
          <div>Application</div>
        </paper-toolbar>
      </paper-header-panel>
      <paper-header-panel main>
        <paper-toolbar>
          <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
          <div>Title</div>
        </paper-toolbar>
        <div>
        </div>
      </paper-header-panel>
    </paper-drawer-panel>
  </neon-animatable>
  <neon-animatable>2</neon-animatable>
  <neon-animatable>3</neon-animatable>
  <neon-animatable>4</neon-animatable>
  <neon-animatable>5</neon-animatable>
</neon-animated-pages>
```

**Comment by senfgurke** [comment]
@blasten You're right... I found the problem. It's necessary that the parent element has not a height of 0px, then the drawer panel is visible....  my fault, sorry.

:host {
        position: absolute;
        width: 100%;
        height: 100%;
        box-sizing: border-box;
      }

It works like a charm...
