### ISSUE TITLE
paper-select event does not fire

### ISSUE THREAD

**Issue by TheDuc** [PolymerElements/paper-drawer-panel#63]
From the source:

> /**
>       \* Fired when the selected panel changes.
>       *
>       \* Listening for this event is an alternative to observing changes in the `selected` attribute.
>       \* This event is fired both when a panel is selected and deselected.
>       \* The `isSelected` detail property contains the selection state.
>       *
>       \* @event paper-select {{isSelected: boolean, item: Object}} detail -
>       \*     isSelected: True for selection and false for deselection.
>       \*     item: The panel that the event refers to.
>       */

I'm listening for the paper-select event, but it never fires. The paper-responsive-change works just fine. With developer tools I can see that the selected attribute does change, but the event never occurs.

**Comment by blasten** [comment]
@TheDuc It should be `iron-select` and `iron-deselect`, and you can access `event.detail.item`.  The docs should be fixed soon, thanks for reporting the issue.

**Comment by TheDuc** [comment]
Thanks! `iron-select` does work.
