### ISSUE TITLE
Error when i put a paper-input inside a paper-drawer-panel

### ISSUE THREAD

**Issue by ypicoleal** [PolymerElements/paper-drawer-panel#70]
_From @ypicoleal on June 16, 2015 23:7_

Hi partners!

when it loads the page, the paper-drawer-panel aligned to the right, i should be collapsed, but instead it charges full loaded. 

when i call the togglePanel function it bumps and then it midly works.

this only happens when there is a paper-input inside a paper-drawer-panel

```
<paper-drawer-panel id="dmenu" responsive-width="1980px" right-drawer>
        <div drawer>
            <paper-toolbar>
                Title
            </paper-toolbar>
            <div id="drawerContent">
                <form id="form" action="http://localhost/site" method="post">  
                      <paper-input floating-label name="id" label="reporte"></paper-input>
                      <paper-input floating-label name="latitud" label="latitud"></paper-input>
                      <paper-input floating-label name="longitud" label="longitud"></paper-input>
                      <paper-input floating-label name="nombre" label="nombre"></paper-input>
                      <paper-textarea floating-label name="descripcion" label="descripcion"></paper-textarea>
                      <input type="hidden" name="basurero"/>
                      <paper-button raised onclick="submitForm()">Enviar</paper-button>
                </form>
            </div>
        </div>
        <div main>
            <paper-icon-button icon="menu" onclick="document.getElementById('dmenu').togglePanel()"></paper-icon-button>
            hello world
        </div>
    </paper-drawer-panel>
```

Please, hope you can help me with this 

_Copied from original issue: Polymer/polymer#1893_

**Comment by ypicoleal** [comment]
_From @sorvell on June 17, 2015 15:1_

This issue tracker is for the Polymer core library. We'll make sure this gets moved to the appropriate repo.

**Comment by blasten** [comment]
@ypicoleal I don't see the issue. If the device width is smaller than 1980px, then the drawer will collapse automatically.  You can also use `forceNarrow` to force the narrow mode regardless of the device width.

e.g.

``` html
<paper-drawer-panel id="dmenu" force-narrow right-drawer>
```

**Comment by ypicoleal** [comment]
Hi @blasten, the error keep happening  regardless of the <code>forceNarrow</code> property, also in the Google Chrome browser does not work, but in the Mozilla Firefox browser everything works just fine and easy. 

For instance, and in a last shot to make it work on Chrome, in the javaScript Console, when i call the function <code>togglePanel</code>, suddenly everything is ok and smell like roses, but the thing is on the load of the page, in that moment does not work at all.

Ps: the <code>iron-page</code> when i use it inside of <code>paper-drawer-panel</code> does not work either.

Hope you can help me with this.

**Comment by blasten** [comment]
@ypicoleal  can you share a link? Did you use vulcanize?

**Comment by blasten** [comment]
Here is an example http://output.jsbin.com/zaxane

**Comment by ypicoleal** [comment]
Bro, after reviewing your code, i noticed that i had the previous version of the libraries, so i update them and every works  just fine!!

thanks mate!
