### ISSUE TITLE
drawerToggleAttribute

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-drawer-panel#71]
if you customize this property, it won't hide the toggle element in narrow layout.

**Comment by kingflurkel** [comment]
Line 238

```
    forceNarrow: {
      type: Boolean,
      value: false,
      notify: true
    },
```

Because notify is not true...

**Comment by Stefdv** [comment]
I added notify:true ...no change. The toggle element will not hide.
as a mather of fact..it looks like the drawer is transparant, everything on the main toolbar is shining tru.
the drawer has a background-color set to white.
Only when i use paper-header-panel everything works , but i don't need the header panel

**Comment by bwh-rl** [comment]
Why is this a wontfix? The issue is still (or again?) around:
https://jsbin.com/kociwujuca/1/edit?html,output

And the docu says clearly that this should work:

> drawerToggleAttribute
> String
> Default: paper-drawer-toggle
> The attribute on elements that should toggle the drawer on tap, also elements will automatically be hidden in wide layout.

As far as i understand this occurs because the hide feature is hardcoded to the default value paper-drawer-toggle:

``` css
      iron-selector:not(.narrow-layout) ::content [paper-drawer-toggle] {
        display: none;
      }
```

**Comment by bwh-rl** [comment]
Is it just me or is this whole `paper-drawer-toggle` incl. the `drawerToggleAttribute` feature a bit non-standard?

**Comment by blasten** [comment]
@bwh-rl There's an alternative. it's app-drawer-layout. [Check it out](https://github.com/PolymerElements/app-layout)
