### ISSUE TITLE
Missing property value

### ISSUE THREAD

**Issue by nonameolsson** [PolymerElements/paper-drawer-panel#74]
I try to use the paper-drawer-panel, but I can't get it to work. I just get this message.
paper-drawer-panel.css:31
`@apply(--paper-drawer-panel-drawer-container);`

Edit:
I use Ruby on Rails 4 also.

Does anyone know why I get this error?
![screenshot from 2015-06-24 09 16 47](https://cloud.githubusercontent.com/assets/1493018/8324533/cff0d238-1a51-11e5-8466-5775cba9debd.png)

**Comment by blasten** [comment]
It seems like Sass is complaining about `@apply`

**Comment by nonameolsson** [comment]
It could be that. Has anyone else tried it with Sass?

**Comment by blasten** [comment]
@addyosmani is there a way to ignore `@apply` in a Sass file?

**Comment by nonameolsson** [comment]
Now it works!
So I created a new rails app and installed everything in order from scratch. It worked!
After that I removed everything from the other app I tried to use before. Now it works!

I have no idea, but Sass doesn't seem complain about the @apply anymore.
