### ISSUE TITLE
Blinking issue on iOS Safari when tapping window on demo

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-drawer-panel#75]
In the demo page, tapping window on iOS Safari results in gray-color blinking issue like this.

![img_0002](https://cloud.githubusercontent.com/assets/1264530/8354251/978b4a32-1b81-11e5-922a-88e0e86b3a2a.png)

**Comment by blasten** [comment]
I thought we fixed this issue. cc @azakus @frankiefu do you remember this issue when you add mouse event listeners on iOS?

**Comment by frankiefu** [comment]
If you add the `-webkit-tap-highlight-color: rgba(0, 0, 0, 0);` to body that should help.

**Comment by naoak** [comment]
It works. Thanks:)
