### ISSUE TITLE
Support two side drawers.

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/paper-drawer-panel#76]
A number of Android applications support a right-hand drawer as well (accessed by the kebab menu). Would it be possible to support this?

**Comment by blasten** [comment]
@PaulHMason do you mean both drawers at the same time? You might get it working by combining two nested paper-drawer-panels.  One with `right-drawer` and the other without it.  
I think it'd be awesome to have a demo with two drawers at the same time.

**Comment by naberly** [comment]
Does it support a left and right drawer not at the same time? I could not get it to work.

**Comment by PaulHMason** [comment]
Yes, you can have either a left or a right drawer - just not both at the same time.

**Comment by blasten** [comment]
that's right. I will keep this issue open until we have a demo :)

**Comment by sandro-k** [comment]
@PaulHMason @blasten this works like is charm

``` html
<paper-drawer-panel drawer-toggle-attribute="paper-drawer-left">
  <div drawer> left drawer panel... </div>
  <div main>
    <paper-drawer-panel drawer-toggle-attribute="paper-drawer-right" right-drawer>
      <div drawer> right drawer panel... </div>
      <div main>
        <button paper-drawer-left>left</button>
        <button paper-drawer-right>right</button>
      </div>
    </paper-drawer-panel>
  </div>
</paper-drawer-panel>
```

Add `paper-drawer-toggle` to the buttons if you want to automatically hide them in wide layout.

**Comment by rajat1saxena** [comment]
@sandro-k your solution saved my day. Thanks

**Comment by radupopa2010** [comment]
@sandro-k  works for me to !!!!!

Question: how did you figure it out how to solve this problem? 

 I appreciate the solution, but please share some wisdom with us :)

**Comment by sandro-k** [comment]
@radupopa2010 Polymer is not a black box.. You always can and should look at the source code! The drawer is absolute positioned and therefore it is irrelevant which drawer comes first.

**Comment by blasten** [comment]
btw, app-layout also supports two drawers https://github.com/PolymerLabs/app-layout/tree/master/app-drawer

**Comment by radupopa2010** [comment]
@sandro-k  I'm a junior developer with just a couple of months experience and would like to understand how Polymer works.
I have looked through the docs and still can't figure it out  how you  you knew to add this custom attribute: _drawer-toggle-attribute="paper-drawer-right"_

**Comment by sandro-k** [comment]
@radupopa2010 Polymer needs a way to determine which drawer should be triggered when a on-click/on-tap event is fired. It is a common pattern to store IDs or identifier in HTML-(data) attributes to express the relationship between elements. I figured it out by reading the code -> https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.html#L490 and https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.html#L673

**Comment by radupopa2010** [comment]
Thank you very much Sanndro. This was really helpful.

Best Regards,

## Radu Gabriel Popa

## E-mail: radupopa2010@yahoo.comMobile: (+1) 619 9404 8022

```
  From: Sanndro <notifications@github.com>
```

 To: PolymerElements/paper-drawer-panel paper-drawer-panel@noreply.github.com 
Cc: radupopa2010 radupopa2010@yahoo.com
 Sent: Tuesday, December 29, 2015 4:26 AM
 Subject: Re: [paper-drawer-panel] Support two side drawers. (#76)

@radupopa2010 Polymer needs a way to determine which drawer should be triggered when a on-click/on-tap event is fired. It is a common pattern to store IDs or identifier in HTML-(data) attributes to express the relationship between elements. I figured it out by reading the code -> https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.html#L490 and https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.html#L673—

**Comment by bhinderbaljeet** [comment]
Thanks allot @sandro-k

**Comment by scottromack** [comment]
Working on a nested demo.

**Comment by sandro-k** [comment]
Nested should work the same way. You mean like two drawers on the same side right?

**Comment by scottromack** [comment]
Two drawers on opposite sides. I have examples of that but it they both need to auto open on desktop and inner content needs to make room.
