### ISSUE TITLE
release version 1.0.3 don't work properly in Firefox

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-drawer-panel#78]
The drawer panel do not work properly in Firefox (tested on Firefox 39.0), the drawer is always closed, no way to show it and the toggle button is always displayed (but don't work too).

The bug can be tested opening the demo page of the current release version (1.0.3) of paper-drawer-panel (/paper-drawer-panel/demo/index.html) on Firefox.

**Comment by kungufli** [comment]
After more investigation, it seems this is Vulcanize fault here. The original demo page works correctly, but it is broken after vulcanization. The strange thing is that in Chrome the vulcanized version still works, but not in Firefox and Safari.

**Comment by blasten** [comment]
@kungufli  hmm. Did you include webcomponents.js?

**Comment by kungufli** [comment]
Sure, both the original index.html demo page and the vulcanized one include the webcomponents-lite.js script import.

**Comment by frankiefu** [comment]
@kungufli Did you inline the external stylesheet? For example, this should work:
`vulcanize --inline-scripts --inline-css index.html > index-vulcanize.html`

**Comment by kungufli** [comment]
@frankiefu Thank you, the --inline-css option did the trick. Now I'm wondering why this option is needed for the page to work on Firefox and Safari but not in Chrome?
