### ISSUE TITLE
on mobile, when scrolling through buttons next tap/touch/input event is lost

### ISSUE THREAD

**Issue by m4b** [PolymerElements/paper-drawer-panel#80]
## Description

I'm raising the issue here because so far, I can only reproduce this in `<paper-drawer-panel>`, but it may well originate somewhere else.

On mobile devices, when scrolling through an `<iron-list>` or `<template is="dom-repeat">` of buttons, _inside_ of a `<paper-drawer-panel>`, the subsequent touch event is "lost", in that for example, if you scroll the list, then tap on an item, or a button elsewhere, the tap event isn't registered by any `on-tap` handlers (although the ink _will_ show, if it's a `<paper-button>`, etc.).

I consider this a fairly serious issue, as it makes the mobile experience extremely unpleasant and seemingly buggy.

**Platforms affected**: Chrome on Android, Firefox on Android, Safari on iOS
### Related Issue for Non-chrome Desktop Browsers

I have also noticed that a touch on a button, which is then dragged off before releasing (to avoid activating the button, for example), will produce a similar issue.  

**Platforms affected**: OSX Firefox, OSX Safari, Chrome on Android, Firefox on Android, Safari on iOS

For example, on Firefox or Safari on OSX, if an item in the problematic list above, or a button is clicked, and then dragged away before releasing, the subsequent click event does not call the `on-tap` handler (but ink effects are generated).
## Steps to Reproduce
1. Create a project with a `<paper-drawer-panel>` and inside of its main content, put an `<iron-list>` or `<template is="dom-repeat">` whose elements are buttons (e.g., `<paper-button>`), which have enough items so that the user can scroll.
2. Also add _another_ button somewhere, say in `<paper-header-panel>`, which does something obvious like a color change, so that it is easy to recognize when the `on-tap` method is called on this button.
3. Scroll through the list of items.  If you're using `<paper-button>` as the elements, you will see ink effects on a touch down.
4. Stop scrolling, and tap the button in 2.  You will notice that whatever logic you put in `on-tap` was not called (but if it was a `<paper-button>` its ink effect was triggered).  The next tap after this works as usual.
## Example

``` html
<dom-module id="parent-panel">
  <style>
  </style>
  <template>
    <paper-drawer-panel>
      <paper-header-panel drawer>
        <paper-toolbar>
          <div>Drawer</div>
        </paper-toolbar>
      </paper-header-panel>
      <paper-header-panel mode="standard" main>
        <paper-toolbar id="toolbar" style$="[[_toolbarStyle]]">
          <paper-button raised on-tap="_changeColor">Tap Me</paper-button>
          <h3>On Mobile Scroll, the next touch is lost</h3>
        </paper-toolbar>
          <iron-list items="[[_items]]">
            <template>
              <paper-button on-tap="_tap">[[item]]</paper-button>
            </template>
        </iron-list>
      </paper-header-panel>
    </paper-drawer-panel>
  </template>
  <script>
    Polymer({
      is: "parent-panel",
      properties: {
        _current: {
          value: 0
        },
        _toolbarStyle: {
          value: 'background: blue;'
        },
        _items: {
          type: Array,
          notify: true,
          value: function() { return [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];}
        }
      },
      _changeColor: function(e){
        console.log('_changeColor');
        this._current = (this._current + 1) % 2;
        this._toolbarStyle = this._current % 2 === 0 ? 'background: blue;' : 'background: red';
      },
      _tap: function(e){
        console.log('tap registered');
      }
    });
  </script>
</dom-module>
```

**Comment by ronnyroeller** [comment]
We're facing the same issue. I agree with @m4b that this is a blocker for mobile. For users it feels like the buttons don't really work.

**Comment by m4b** [comment]
I've just verified the issue is caused by this element adding a listener for `track`; when the `track: '_onTrack'` line is removed in the listeners object in `<paper-drawer-panel>` the issue goes away.

Leaving the listener in and commenting all the code in `_onTrack` does **not** remove the issue; as such, this suggests it has to do with an issue in Polymer itself, probably a flaw somewhere in the gesture libraries.

**Comment by m4b** [comment]
This will be fixed when [whichever](https://github.com/Polymer/polymer/pull/2116) [fix](https://github.com/Polymer/polymer/pull/2117) for Polymer/polymer#2065 is merged.

**Comment by blasten** [comment]
@m4b thanks for reporting the issue. I will chat with @azakus about this.

**Comment by m4b** [comment]
@blasten: np, but it's basically a duplicate of Polymer/polymer#2065; when that patch goes through, I believe it'll clear up.

**Comment by blasten** [comment]
This should be fixed in master now. https://github.com/Polymer/polymer/pull/2124
