### ISSUE TITLE
paper-drawer-panel and Turbolinks doesn't work

### ISSUE THREAD

**Issue by nonameolsson** [PolymerElements/paper-drawer-panel#82]
I have a web app with Rails 4 and Turbolinks, https://github.com/rails/turbolinks. Now I've started to add more Polymer elements to the app. But I can't get `paper-drawer-panel` to work.
When loading the page the first time everything looks and behaves as expected. But when clicking a link the problem starts. I made a video of the problem. 
https://www.youtube.com/watch?v=Zqtn9uxI1xs

It seems like the `paper-drawer-panel` isn't populated with the content after changing page with Turbolinks. I don't think this is a problem with Turbolinks, but more a result of how it works and how `paper-drawer-panel` works. 
I don't really understand how paper-drawer-panel works and load it's content. Therefore I haven't been able to figure out a solution.

But a while ago I had the same problem with `jquery.mmenu` and Turbolinks. 
Problem: https://github.com/BeSite/jQuery.mmenu/issues/41
Solution: http://mmenu.frebsite.nl/tutorials/frameworks/turbolinks.html

Could it be a similar solution to get `paper-drawer-panel` to work with Turbolinks? All help is appreciated. I really need this one to work in our app, and disabling Turbolinks isn't an option.

UPDATE:
Here is some code.
`application.html.haml`

```
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
%html
  = render 'layouts/head'

  %body{class: "#{body_classes(yield :body_classes)}fullbleed layout vertical"}
    - if current_user
      = render 'layouts/content'
      = render 'shared/notifications'

    - else
      = render 'shared/notifications'
      = yield

    / outdated-browser
    #outdated= render "layouts/outdatedbrowser/#{I18n.locale}"
```

`layouts/_content.html.haml`

```
/ Page Content
%paper-drawer-panel
  %div{:drawer => ""}
    = render 'layouts/menu'

  %div{:main => ""}
    %paper-header-panel{:drawer => ""}
      %paper-toolbar
        %paper-icon-button{:icon => "menu", "paper-drawer-toggle" => ""}
        %div= current_title(yield(:title))
      = yield
```

**Comment by blasten** [comment]
@nonameolsson I don't see how `paper-drawer-panel` could be causing the issue. It seems like the whole page is refreshed after you clicked the link. You might want to call `preventDefault` on the click event. e.g.

``` js
document.querySelector('[drawer]').addEventListener('click', function(e) {
   e.preventDefault();
});
```

**Comment by blasten** [comment]
I am closing this. please reopen if you have an update.
