### ISSUE TITLE
responsiveWidth doesn't work on Firefox

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-drawer-panel#85]
For example:

``` js
a = document.querySelector("#drawer-container");
a.responsiveWidth = "800px";
$(window).width(); // Returns 717
```

Yet, no collapse.

![screenshot 61](https://cloud.githubusercontent.com/assets/165937/9193572/4b07fe3c-3fc9-11e5-90e4-a07ee6325dd6.png)

Works in Edge, Chrome (shown side-by-side). Safari on desktop hasn't been tested yet, though Safari on iOS also shows an expanded drawer.

**Comment by blasten** [comment]
I couldn't replicate this issue. http://output.jsbin.com/kolehu 
Can you share the code that is causing the problem?

**Comment by blasten** [comment]
ping

**Comment by tigerhawkvok** [comment]
Whoops! Thanks for the ping.

I was writing up a reduced test case for you, and it seems to have been incidentally fixed between then and now.
