### ISSUE TITLE
Paper drawer panel does not support RTL languages

### ISSUE THREAD

**Issue by rogerta** [PolymerElements/paper-drawer-panel#90]
paper-drawer-panel does not support RTL languages.  When used in a page with:

`<html dir="RTL">...</html>`

the drawer still appears on the left side.  Adding an attached() callback like this seems to fix the problem:

```
  attached: function() {
    if (document.documentElement.dir === 'rtl')
      this.rightDrawer = !this.rightDrawer;
  }
```

I believe doing this would match the android drawer behaviour for RTL languages: https://developer.android.com/training/implementing-navigation/nav-drawer.html

(Instead of using terms "left" and "right", might be better to use "start" and "end".)

**Comment by blasten** [comment]
For RTL, you can also use:
`<paper-drawer-pane right-drawer></paper-drawer-panel>`  
Thanks for the suggestion!

**Comment by rogerta** [comment]
Hey Emmanuel, you completely missed the point :-)  I know that I can set the drawer to the right side myself, but the problem is exactly that: I need to set the drawer to the right side myself.  My suggestion is that paper-drawer-panel should be smart enough to do the right thing without my intervention.  For example, if I use the right-drawer or left-drawer attribute explicitly, it should do as stated.  But if I leave both out, then it should use the correct side based on the direction of the page.

**Comment by blasten** [comment]
I know, the problem is that there could be cases in which you actually want two drawers (left & right). which means that we will have to flip the value for both drawer depending on the document's `dir` attribute. At this point, the user loses the ability to decide in which side the drawer should be in. We could have another attribute to capture this behavior. e.g. `<paper-drawer-panel document-dir>`

**Comment by rogerta** [comment]
That makes sense. So if I don't explicitly set document-dir, does your proposal mean the drawer panel will follow the top level document direction?
